/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2023-05-12 07:36:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>ATS</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <title>ATS - WEB base Billing System</title>\r\n");
      out.write("    <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("    <meta content=\"\" name=\"keywords\">\r\n");
      out.write("    <meta content=\"\" name=\"description\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("    <link href=\"img/favicon.ico\" rel=\"icon\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Web Fonts -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link\r\n");
      out.write("        href=\"https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500;600&family=Rubik:wght@500;600;700&display=swap\"\r\n");
      out.write("        rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Icon Font Stylesheet -->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Libraries Stylesheet -->\r\n");
      out.write("    <link href=\"lib/animate/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Stylesheet -->\r\n");
      out.write("    <link href=\"css/admine.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");

    if(session.getAttribute("user")!=null){
    	String snm = session.getAttribute("snm").toString();
	String usnm=session.getAttribute("user").toString();
	System.out.println(usnm);
    
    
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!-- Spinner Start -->\r\n");
      out.write("    <div id=\"spinner\"\r\n");
      out.write("        class=\"show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center\">\r\n");
      out.write("        <div class=\"spinner-border text-primary\" role=\"status\" style=\"width: 3rem; height: 3rem;\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Spinner End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Topbar Start -->\r\n");
      out.write("    <div class=\"container-fluid bg-dark px-0\">\r\n");
      out.write("        <div class=\"row g-0 d-none d-lg-flex\">\r\n");
      out.write("            <div class=\"col-lg-6 ps-5 text-start\">\r\n");
      out.write("                <div class=\"h-100 d-inline-flex align-items-center text-white\">\r\n");
      out.write("                    <span>Follow Us:</span>\r\n");
      out.write("                    <a class=\"btn btn-link text-light\" href=\"\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                    <a class=\"btn btn-link text-light\" href=\"\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                    <a class=\"btn btn-link text-light\" href=\"\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                    <a class=\"btn btn-link text-light\" target=\"_blank\" href=\"https://www.instagram.com/billing_with_ats/\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Topbar End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Navbar Start -->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg bg-white navbar-light sticky-top py-0 pe-5\">\r\n");
      out.write("        <a href=\"index.html\" class=\"navbar-brand ps-5 me-0\">\r\n");
      out.write("            <h1 class=\"text-white m-0\"><img src=\"img/logoo.png\" alt=\"\" width=\"102\" height=\"79\"></h1>\r\n");
      out.write("        </a>\r\n");
      out.write("        <button type=\"button\" class=\"navbar-toggler me-0\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarCollapse\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarCollapse\">\r\n");
      out.write("            <div class=\"navbar-nav ms-auto p-4 p-lg-0\">\r\n");
      out.write("                <a href=\"index.html\" class=\"nav-item nav-link active\">Home</a>\r\n");
      out.write("                <a href=\"about.html\" class=\"nav-item nav-link\">About</a>\r\n");
      out.write("                <a href=\"service.jsp\" class=\"nav-item nav-link\">Services</a>\r\n");
      out.write("                <a href=\"contact.html\" class=\"nav-item nav-link\">Contact</a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <a href=\"/Indsutrio-1.0.0/login.html\" class=\"btn btn-primary px-3 d-none d-lg-block\">");
      out.print( session.getAttribute("user") );
      out.write("!</a>\r\n");
      out.write("                \r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <!-- Navbar End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Carousel Start -->\r\n");
      out.write("    <div class=\"container-fluid px-0 mb-5\">\r\n");
      out.write("        <div id=\"header-carousel\" class=\"carousel slide\" data-bs-ride=\"carousel\">\r\n");
      out.write("            <div class=\"carousel-inner\">\r\n");
      out.write("                <div class=\"carousel-item active\">\r\n");
      out.write("                    <img class=\"w-100\" src=\"img/Business medical meeting.jpg\" alt=\"Image\"  width=\"900\" height=\"650\">\r\n");
      out.write("                    <div class=\"carousel-caption\">\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                            <div class=\"row justify-content-center\">\r\n");
      out.write("                                <div class=\"col-lg-10 text-start\">\r\n");
      out.write("                                    <p class=\"fs-5 fw-medium text-primary text-uppercase animated slideInRight\">6 Month\r\n");
      out.write("                                        of Working Experience</p>\r\n");
      out.write("                                    <h1 class=\"display-1 text-white mb-5 animated slideInRight\">Medical Store Billing Software</h1>\r\n");
      out.write("                                    <a href=\"\" class=\"btn btn-primary py-3 px-5 animated slideInRight\">Explore More</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"carousel-item\">\r\n");
      out.write("                    <img class=\"w-100\" src=\"img/Business executive holding blank placard.jpg\" alt=\"Image\" width=\"900\" height=\"650\">\r\n");
      out.write("                    <div class=\"carousel-caption\">\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                            <div class=\"row justify-content-center\">\r\n");
      out.write("                                <div class=\"col-lg-10 text-start\">\r\n");
      out.write("                                    <p class=\"fs-5 fw-medium text-primary text-uppercase animated slideInRight\">6 Month\r\n");
      out.write("                                        of Working Experience</p>\r\n");
      out.write("                                    <h1 class=\"display-1 text-white mb-5 animated slideInRight\">The Best Reliable\r\n");
      out.write("                                        Billing Solution</h1>\r\n");
      out.write("                                    <a href=\"\" class=\"btn btn-primary py-3 px-5 animated slideInRight\">Explore More</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#header-carousel\" data-bs-slide=\"prev\">\r\n");
      out.write("                <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("                <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#header-carousel\" data-bs-slide=\"next\">\r\n");
      out.write("                <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("                <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Carousel End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- Service Start -->\r\n");
      out.write("  <div class=\"container-xxl py-5\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"text-center mx-auto pb-4 wow fadeInUp\" data-wow-delay=\"0.1s\" style=\"max-width: 600px;\">\r\n");
      out.write("            <p class=\"fw-medium text-uppercase text-primary mb-2\">Our Services</p>\r\n");
      out.write("            <h1 class=\"display-5 mb-4\">We Provide Best Industrial Services</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row gy-5 gx-4\">\r\n");
      out.write("            <div class=\"col-md-6 col-lg-4 wow fadeInUp\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                <div class=\"service-item\">\r\n");
      out.write("                    <img class=\"img-fluid\" src=\"img/medibhai.png\" alt=\"\">\r\n");
      out.write("                    <div class=\"service-img\">\r\n");
      out.write("                        <img class=\"img-fluid\" src=\"img/medibhai.png\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"service-detail\">\r\n");
      out.write("                        <div class=\"service-title\">\r\n");
      out.write("                            <hr class=\"w-25\">\r\n");
      out.write("                            <h3 class=\"mb-0\">Client are Happy</h3>\r\n");
      out.write("                            <hr class=\"w-25\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"service-text\">\r\n");
      out.write("                            <p class=\"text-white mb-0\">This software is designed to simplify and automate the\r\n");
      out.write("                                billing process of these stores, making it easier for them to manage their inventory\r\n");
      out.write("                                and financial transactions.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <a class=\"btn btn-light\" href=\"\">Read More</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-6 col-lg-4 wow fadeInUp\" data-wow-delay=\"0.3s\">\r\n");
      out.write("                <div class=\"service-item\">\r\n");
      out.write("                    <img class=\"img-fluid\" src=\"img/medib2b.png\" alt=\"\">\r\n");
      out.write("                    <div class=\"service-img\">\r\n");
      out.write("                        <img class=\"img-fluid\" src=\"img/medib2b.png\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"service-detail\">\r\n");
      out.write("                        <div class=\"service-title\">\r\n");
      out.write("                            <hr class=\"w-25\">\r\n");
      out.write("                            <h3 class=\"mb-0\">Staff is Happy</h3>\r\n");
      out.write("                            <hr class=\"w-25\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"service-text\">\r\n");
      out.write("                            <p class=\"text-white mb-0\">With a medical store billing system, staff can quickly and\r\n");
      out.write("                                easily generate bills for customers, keep track of inventory levels, and monitor\r\n");
      out.write("                                sales trends.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <a class=\"btn btn-light\" href=\"\">Read More</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-6 col-lg-4 wow fadeInUp\" data-wow-delay=\"0.5s\">\r\n");
      out.write("                <div class=\"service-item\">\r\n");
      out.write("                    <img class=\"img-fluid\" src=\"img/newhap.png\" alt=\"\">\r\n");
      out.write("                    <div class=\"service-img\">\r\n");
      out.write("                        <img class=\"img-fluid\" src=\"img/newhap.png\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"service-detail\">\r\n");
      out.write("                        <div class=\"service-title\">\r\n");
      out.write("                            <hr class=\"w-25\">\r\n");
      out.write("                            <h3 class=\"mb-0\">B to B is Happy</h3>\r\n");
      out.write("                            <hr class=\"w-25\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"service-text\">\r\n");
      out.write("                            <p class=\"text-white mb-0\">Such a system could provide a number of benefits to the\r\n");
      out.write("                                business, including streamlined operations, improved accuracy in billing and\r\n");
      out.write("                                inventory management, and increased efficiency in handling orders and payments.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <a class=\"btn btn-light\" href=\"\">Read More</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Service End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- Project Start -->\r\n");
      out.write("  <div class=\"container-fluid bg-dark pt-5 my-5 px-0\">\r\n");
      out.write("    <div class=\"text-center mx-auto mt-5 wow fadeIn\" data-wow-delay=\"0.1s\" style=\"max-width: 600px;\">\r\n");
      out.write("        <p class=\"fw-medium text-uppercase text-primary mb-2\">Our Projects</p>\r\n");
      out.write("        <h1 class=\"display-5 text-white mb-5\">See What We Have Completed Recently</h1>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"owl-carousel project-carousel wow fadeIn\" data-wow-delay=\"0.1s\">\r\n");
      out.write("        <a class=\"project-item\" href=\"\">\r\n");
      out.write("            <img class=\"img-fluid\" src=\"img/medibhai.png\" alt=\"\">\r\n");
      out.write("            <div class=\"project-title\">\r\n");
      out.write("                <h5 class=\"text-primary mb-0\">Billing process is happy</h5>\r\n");
      out.write("            </div>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a class=\"project-item\" href=\"\">\r\n");
      out.write("            <img class=\"img-fluid\" src=\"img/bdk.jpg\" alt=\"\">\r\n");
      out.write("            <div class=\"project-title\">\r\n");
      out.write("                <h5 class=\"text-primary mb-0\">***</h5>\r\n");
      out.write("            </div>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a class=\"project-item\" href=\"\">\r\n");
      out.write("            <img class=\"img-fluid\" src=\"img/medib2b.png\" alt=\"\">\r\n");
      out.write("            <div class=\"project-title\">\r\n");
      out.write("                <h5 class=\"text-primary mb-0\">B to B is happy</h5>\r\n");
      out.write("            </div>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a class=\"project-item\" href=\"\">\r\n");
      out.write("            <img class=\"img-fluid\" src=\"img/bc.jpg\" alt=\"\">\r\n");
      out.write("            <div class=\"project-title\">\r\n");
      out.write("                <h5 class=\"text-primary mb-0\">****</h5>\r\n");
      out.write("            </div>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a class=\"project-item\" href=\"\">\r\n");
      out.write("            <img class=\"img-fluid\" src=\"img/happystaff.png\" alt=\"\">\r\n");
      out.write("            <div class=\"project-title\">\r\n");
      out.write("                <h5 class=\"text-primary mb-0\">Staff is happy</h5>\r\n");
      out.write("            </div>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a class=\"project-item\" href=\"\">\r\n");
      out.write("            <img class=\"img-fluid\" src=\"img/bs.jpg\" alt=\"\">\r\n");
      out.write("            <div class=\"project-title\">\r\n");
      out.write("                <h5 class=\"text-primary mb-0\">***</h5>\r\n");
      out.write("            </div>\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Project End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <!-- Testimonial Start -->\r\n");
      out.write("   <div class=\"container-xxl py-5\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"text-center mx-auto wow fadeInUp\" data-wow-delay=\"0.1s\" style=\"max-width: 600px;\">\r\n");
      out.write("            <p class=\"fw-medium text-uppercase text-primary mb-2\">Testimonial</p>\r\n");
      out.write("            <h1 class=\"display-5 mb-5\">What Our Clients Say!</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"owl-carousel testimonial-carousel wow fadeInUp\" data-wow-delay=\"0.1s\">\r\n");
      out.write("            <div class=\"testimonial-item text-center\">\r\n");
      out.write("                <div class=\"testimonial-img position-relative\">\r\n");
      out.write("                    <img class=\"img-fluid rounded-circle mx-auto mb-5\" src=\"img/nishu.jpg\">\r\n");
      out.write("                    <div class=\"btn-square bg-primary rounded-circle\">\r\n");
      out.write("                        <i class=\"fa fa-quote-left text-white\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"testimonial-text text-center rounded p-4\">\r\n");
      out.write("                    <p>Mobile-friendly: A large percentage of users access the internet using their mobile devices.\r\n");
      out.write("                        Therefore, ensure that your website is mobile-friendly and responsive to different screen\r\n");
      out.write("                        sizes.</p>\r\n");
      out.write("                    <h5 class=\"mb-1\">Client Name</h5>\r\n");
      out.write("                    <span class=\"fst-italic\">Profession</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"testimonial-item text-center\">\r\n");
      out.write("                <div class=\"testimonial-img position-relative\">\r\n");
      out.write("                    <img class=\"img-fluid rounded-circle mx-auto mb-5\" src=\"img/karm.jpg\">\r\n");
      out.write("                    <div class=\"btn-square bg-primary rounded-circle\">\r\n");
      out.write("                        <i class=\"fa fa-quote-left text-white\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"testimonial-text text-center rounded p-4\">\r\n");
      out.write("                    <p>Functionality: The website should be fully functional and easy to use. Ensure that the\r\n");
      out.write("                        billing process is smooth and efficient. It should be easy for the user to add items to the\r\n");
      out.write("                        cart, review their order, and complete the payment process.</p>\r\n");
      out.write("                    <h5 class=\"mb-1\">Karamveer Singh</h5>\r\n");
      out.write("                    <span class=\"fst-italic\">Student</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"testimonial-item text-center\">\r\n");
      out.write("                <div class=\"testimonial-img position-relative\">\r\n");
      out.write("                    <img class=\"img-fluid rounded-circle mx-auto mb-5\" src=\"img/prathmesh.jpg\">\r\n");
      out.write("                    <div class=\"btn-square bg-primary rounded-circle\">\r\n");
      out.write("                        <i class=\"fa fa-quote-left text-white\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"testimonial-text text-center rounded p-4\">\r\n");
      out.write("                    <p>Security: Security is a significant concern for online transactions, especially when it comes\r\n");
      out.write("                        to medical information. Ensure that the website is secure and that the user's personal\r\n");
      out.write("                        information is kept confidential.</p>\r\n");
      out.write("                    <h5 class=\"mb-1\">Khanda Bhau</h5>\r\n");
      out.write("                    <span class=\"fst-italic\">Student</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Testimonial End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Footer Start -->\r\n");
      out.write("    <div class=\"container-fluid bg-dark footer mt-5 py-5 wow fadeIn\" data-wow-delay=\"0.1s\">\r\n");
      out.write("        <div class=\"container py-5\">\r\n");
      out.write("            <div class=\"row g-5\">\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                    <h5 class=\"text-white mb-4\">Our Office</h5>\r\n");
      out.write("                    <p class=\"mb-2\"><i class=\"fa fa-map-marker-alt me-3\"></i>Gulshan tower,amravati</p>\r\n");
      out.write("                    <p class=\"mb-2\"><i class=\"fa fa-phone-alt me-3\"></i>+012 345 67890</p>\r\n");
      out.write("                    <p class=\"mb-2\"><i class=\"fa fa-envelope me-3\"></i>info@example.com</p>\r\n");
      out.write("                    <div class=\"d-flex pt-3\">\r\n");
      out.write("                        <a class=\"btn btn-square btn-primary rounded-circle me-2\" href=\"\"><i\r\n");
      out.write("                                class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                        <a class=\"btn btn-square btn-primary rounded-circle me-2\" href=\"\"><i\r\n");
      out.write("                                class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                        <a class=\"btn btn-square btn-primary rounded-circle me-2\" href=\"\"><i\r\n");
      out.write("                                class=\"fab fa-youtube\"></i></a>\r\n");
      out.write("                        <a class=\"btn btn-square btn-primary rounded-circle me-2\" href=\"\"><i\r\n");
      out.write("                                class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                    <h5 class=\"text-white mb-4\">Quick Links</h5>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"about.html\">About Us</a>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"contact.html\">Contact Us</a>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"servicepg.html\">Our Services</a>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"\">Terms & Condition</a>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"contact.html\">Support</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                    <h5 class=\"text-white mb-4\">lorem8</h5>\r\n");
      out.write("                    <p class=\"mb-1\">Monday - Friday</p>\r\n");
      out.write("                    <h6 class=\"text-light\"></h6>\r\n");
      out.write("                    <p class=\"mb-1\">Saturday</p>\r\n");
      out.write("                    <h6 class=\"text-light\"></h6>\r\n");
      out.write("                    <p class=\"mb-1\">Sunday</p>\r\n");
      out.write("                    <h6 class=\"text-light\"></h6>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                    <h5 class=\"text-white mb-4\">FeedBack</h5>\r\n");
      out.write("                    <p>Type anything that you want to share with us.</p>\r\n");
      out.write("                    <div class=\"position-relative w-100\">\r\n");
      out.write("                        <input class=\"form-control bg-transparent w-100 py-3 ps-4 pe-5\" type=\"text\"\r\n");
      out.write("                            placeholder=\"feedback\">\r\n");
      out.write("                        <a href=\"logout.jsp\" class=\"btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2\">LogOut!</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Footer End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Copyright Start -->\r\n");
      out.write("    <div class=\"container-fluid copyright bg-dark py-4\">\r\n");
      out.write("        <div class=\"container text-center\">\r\n");
      out.write("            <p class=\"mb-2\">Copyright &copy; <a class=\"fw-semi-bold\" href=\"#\">ATS Pvt Lmt</a>, All Right Reserved.\r\n");
      out.write("            </p>\r\n");
      out.write("            <!--/*** This template is free as long as you keep the footer authorâs credit link/attribution link/backlink. If you'd like to use the template without the footer authorâs credit link/attribution link/backlink, you can purchase the Credit Removal License from \"https://htmlcodex.com/credit-removal\". Thank you for your support. ***/-->\r\n");
      out.write("            <p class=\"mb-0\">Designed By<a class=\"fw-semi-bold\" href=\"https:\">Team medical store biling system</a>@Copyright: Tushar, Ayush, and Sahil. <a href=\"https://themewagon.com\"></a> </p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Copyright End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Back to Top -->\r\n");
      out.write("    <a href=\"#\" class=\"btn btn-lg btn-primary btn-lg-square rounded-circle back-to-top\"><i\r\n");
      out.write("            class=\"bi bi-arrow-up\"></i></a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- JavaScript Libraries -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/wow/wow.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/easing/easing.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/waypoints/waypoints.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/owlcarousel/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/counterup/counterup.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Javascript -->\r\n");
      out.write("    <script src=\"js/main.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        document.getElementById(\"logout\").addEventListener(\"click\", function(event) {\r\n");
      out.write("          event.preventDefault();\r\n");
      out.write("          if (confirm(\"Are you sure you want to log out?\")) {\r\n");
      out.write("            // send an HTTP request to invalidate the session on the server\r\n");
      out.write("            var xhr = new XMLHttpRequest();\r\n");
      out.write("            xhr.open(\"GET\", \"logout.jsp\", true);\r\n");
      out.write("            xhr.onload = function() {\r\n");
      out.write("              if (xhr.readyState == 4 && xhr.status == 200) {\r\n");
      out.write("                // redirect the user to the login page\r\n");
      out.write("                window.location.href = \"index.html\";\r\n");
      out.write("              }\r\n");
      out.write("            };\r\n");
      out.write("            xhr.send();\r\n");
      out.write("          }\r\n");
      out.write("      Â Â });\r\n");
      out.write("    </script>\r\n");
      out.write("    ");

    }
    else{
     	
      out.write("\r\n");
      out.write("    	<h2>Invalid session...</h2>\r\n");
      out.write("    	<hr>\r\n");
      out.write("    	<p>You are not authorized to see this information.</p>\r\n");
      out.write("    	<a href=\"login.html\">Login</a>\r\n");
      out.write("    	");

    }
    

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
