/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2023-05-12 07:27:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class staff_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<title>Staff Status</title>\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"css/staff.css\">\r\n");
      out.write("	\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("    <meta content=\"\" name=\"keywords\">\r\n");
      out.write("    <meta content=\"\" name=\"description\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("    <link href=\"img/favicon.ico\" rel=\"icon\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Web Fonts -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link\r\n");
      out.write("        href=\"https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500;600&family=Rubik:wght@500;600;700&display=swap\"\r\n");
      out.write("        rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Icon Font Stylesheet -->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Libraries Stylesheet -->\r\n");
      out.write("    <link href=\"lib/animate/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Stylesheet -->\r\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("	\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Spinner End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Topbar Start -->\r\n");
      out.write("    <div class=\"container-fluid bg-dark px-0\">\r\n");
      out.write("        <div class=\"row g-0 d-none d-lg-flex\">\r\n");
      out.write("            <div class=\"col-lg-6 ps-5 text-start\">\r\n");
      out.write("                <div class=\"h-100 d-inline-flex align-items-center text-white\">\r\n");
      out.write("                    <span>Follow Us:</span>\r\n");
      out.write("                    <a class=\"btn btn-link text-light\" href=\"\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                    <a class=\"btn btn-link text-light\" href=\"\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                    <a class=\"btn btn-link text-light\" href=\"\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                    <a class=\"btn btn-link text-light\" target=\"_blank\"\r\n");
      out.write("                        href=\"https://www.instagram.com/billing_with_ats/\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Topbar End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Navbar Start -->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg bg-white navbar-light sticky-top py-0 pe-5\">\r\n");
      out.write("        <a href=\"index.html\" class=\"navbar-brand ps-5 me-0\">\r\n");
      out.write("            <h1 class=\"text-white m-0\"><img src=\"img/logoo.png\" alt=\"\" width=\"102\" height=\"79\"></h1>\r\n");
      out.write("        </a>\r\n");
      out.write("        <button type=\"button\" class=\"navbar-toggler me-0\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarCollapse\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarCollapse\">\r\n");
      out.write("            <div class=\"navbar-nav ms-auto p-4 p-lg-0\">\r\n");
      out.write("                 <a href=\"about.html\" class=\"nav-item nav-link\">About</a>\r\n");
      out.write("                <a href=\"servicepg.html\" class=\"nav-item nav-link\">Services</a>\r\n");
      out.write("                <a href=\"contact.html\" class=\"nav-item nav-link\">Contact</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <a href=\"/Indsutrio-1.0.0/login.html\" class=\"btn btn-primary px-3 d-none d-lg-block\">Login</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <!-- Navbar End -->\r\n");
      out.write("</body>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<h1>Staff Status</h1>\r\n");
      out.write("		<table id=\"staff-table\">\r\n");
      out.write("			<thead>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th style=\"color:rgb(255, 255, 255);\"><h3 style=\"font-size:20px;\">Name</h3></th>\r\n");
      out.write("					<th style=\"color:rgb(255, 255, 255);\"><h3 style=\"font-size:20px;\">joining-date</h3></th>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</thead>\r\n");
      out.write("			<tbody>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>John Doe</td>\r\n");
      out.write("					<td>01/01/2020</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>Jane Doe</td>\r\n");
      out.write("					<td>01/02/2020</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</tbody>\r\n");
      out.write("		</table>\r\n");
      out.write("	<button id=\"add-staff-btn\">Add Staff</button>\r\n");
      out.write("        \r\n");
      out.write("        <div id=\"add-staff-modal\" class=\"modal\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <span class=\"close\">&times;</span>\r\n");
      out.write("                <h2>Add Staff</h2>\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                <form method=\"post\" id=\"add-staff-form\">\r\n");
      out.write("                    <label for=\"name\" class=\"staff-name\">Name:</label>\r\n");
      out.write("                    <input type=\"text\" id=\"name\" name=\"name\" required>\r\n");
      out.write("                    \r\n");
      out.write("                    <label for=\"joining-date\">Joining Date:</label>\r\n");
      out.write("                    <input type=\"date\" id=\"joining-date\" name=\"joining-date\" required>\r\n");
      out.write("                    \r\n");
      out.write("                    <label for=\"mobile-number\">Mobile Number:</label>\r\n");
      out.write("                    <input type=\"tel\" id=\"mobile-number\" name=\"mobile-number\" required>\r\n");
      out.write("                    \r\n");
      out.write("                    <button type=\"submit\">Add</button>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("\r\n");
      out.write("    \r\n");

    String name = request.getParameter("name");
    String joiningdate = request.getParameter("joining_date");
    String mobile = request.getParameter("mobile_number");
    

    if(name != null && joiningdate != null && mobile != null) {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://u95bkzftvx8tpees:XQG18W1E6DvpJgMSS77Y@bpgcz0m5wxumvwiokehb-mysql.services.clever-cloud.com:3306/bpgcz0m5wxumvwiokehb", "root", "password");

            String query = "INSERT INTO users (name, joiningdate, mobile) VALUES (?, ?, ?)";
            
            PreparedStatement statement = con.prepareStatement(query);
            
            statement.setString(1, name);
            statement.setString(2, joiningdate);
            statement.setString(3, mobile);
            statement.executeUpdate();

            con.close();

            System.out.println("<p>Staff member added successfully.</p>");
        } catch(Exception e) {
            System.out.println("<p>Error adding staff member.</p>");
            e.printStackTrace();
        }
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("	    <button id=\"remove-staff-btn\">remove staff</button>\r\n");
      out.write("	</div>\r\n");
      out.write("	        <div id=\"remove-staff-modal\" class=\"model\">\r\n");
      out.write("	            <div class=\"modal-content\">\r\n");
      out.write("	                <span class=\"closs\">&times;</span>\r\n");
      out.write("	                <h2>Add Staff</h2>\r\n");
      out.write("	                <form id=\"remove-staff-form\">\r\n");
      out.write("	\r\n");
      out.write("	                    <label for=\"name\">Name:</label>\r\n");
      out.write("	                    <!-- <input type=\"text\" id=\"name\" name=\"name\" required> -->\r\n");
      out.write("	                    <select id=\"staff-name\" name=\"staff-name\">\r\n");
      out.write("	                        <option value=\"john-doe\">John Doe</option>\r\n");
      out.write("	                        <option value=\"jane-smith\">Jane Smith</option>\r\n");
      out.write("	                        <option value=\"mark-johnson\">Mark Johnson</option>\r\n");
      out.write("	                    </select>\r\n");
      out.write("	\r\n");
      out.write("	                    <label for=\"mobile-number\" >Mobile Number:</label>\r\n");
      out.write("	                    <input type=\"tel\" id=\"mobile-number\" name=\"mobile-number\" required>\r\n");
      out.write("	\r\n");
      out.write("	                    <button type=\"submit\">Add</button>\r\n");
      out.write("	                </form>\r\n");
      out.write("	            </div>\r\n");
      out.write("	        </div>\r\n");
      out.write("\r\n");
      out.write("	<script src=\"js/staff.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
